server:
  port: 8002

spring:
  application:
    name: fgh_tech_order
  datasource:
    url: jdbc:mysql://localhost:3306/fgh_tech_order
    username: root
    password: hiskel1288
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

